//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/sun_t/BotegyApp/Assets/Scripts/CodeParser\ParserGrammar.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ParserGrammarParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface IParserGrammarVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserGrammarParser.ident"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdent([NotNull] ParserGrammarParser.IdentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserGrammarParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCall([NotNull] ParserGrammarParser.CallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Value</c>
	/// labeled alternative in <see cref="ParserGrammarParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] ParserGrammarParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Braces</c>
	/// labeled alternative in <see cref="ParserGrammarParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBraces([NotNull] ParserGrammarParser.BracesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Function</c>
	/// labeled alternative in <see cref="ParserGrammarParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] ParserGrammarParser.FunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Identifier</c>
	/// labeled alternative in <see cref="ParserGrammarParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] ParserGrammarParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserGrammarParser.mult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMult([NotNull] ParserGrammarParser.MultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserGrammarParser.add"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdd([NotNull] ParserGrammarParser.AddContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserGrammarParser.compare1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompare1([NotNull] ParserGrammarParser.Compare1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserGrammarParser.compare2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompare2([NotNull] ParserGrammarParser.Compare2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserGrammarParser.logical_and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogical_and([NotNull] ParserGrammarParser.Logical_andContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserGrammarParser.logical_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogical_or([NotNull] ParserGrammarParser.Logical_orContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserGrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] ParserGrammarParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserGrammarParser.assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssign([NotNull] ParserGrammarParser.AssignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserGrammarParser.simple_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_stmt([NotNull] ParserGrammarParser.Simple_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserGrammarParser.composite"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComposite([NotNull] ParserGrammarParser.CompositeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserGrammarParser.if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf([NotNull] ParserGrammarParser.IfContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserGrammarParser.while"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile([NotNull] ParserGrammarParser.WhileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserGrammarParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmt([NotNull] ParserGrammarParser.StmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserGrammarParser.stmt_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmt_list([NotNull] ParserGrammarParser.Stmt_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserGrammarParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] ParserGrammarParser.ProgramContext context);
}
