//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/sun_t/BotegyApp/Assets/Scripts/CodeParser\ParserGrammar.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ParserGrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface IParserGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserGrammarParser.ident"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdent([NotNull] ParserGrammarParser.IdentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserGrammarParser.ident"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdent([NotNull] ParserGrammarParser.IdentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserGrammarParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCall([NotNull] ParserGrammarParser.CallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserGrammarParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCall([NotNull] ParserGrammarParser.CallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Value</c>
	/// labeled alternative in <see cref="ParserGrammarParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] ParserGrammarParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Value</c>
	/// labeled alternative in <see cref="ParserGrammarParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] ParserGrammarParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Braces</c>
	/// labeled alternative in <see cref="ParserGrammarParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBraces([NotNull] ParserGrammarParser.BracesContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Braces</c>
	/// labeled alternative in <see cref="ParserGrammarParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBraces([NotNull] ParserGrammarParser.BracesContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Function</c>
	/// labeled alternative in <see cref="ParserGrammarParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction([NotNull] ParserGrammarParser.FunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Function</c>
	/// labeled alternative in <see cref="ParserGrammarParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction([NotNull] ParserGrammarParser.FunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Identifier</c>
	/// labeled alternative in <see cref="ParserGrammarParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] ParserGrammarParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Identifier</c>
	/// labeled alternative in <see cref="ParserGrammarParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] ParserGrammarParser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserGrammarParser.mult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMult([NotNull] ParserGrammarParser.MultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserGrammarParser.mult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMult([NotNull] ParserGrammarParser.MultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserGrammarParser.add"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdd([NotNull] ParserGrammarParser.AddContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserGrammarParser.add"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdd([NotNull] ParserGrammarParser.AddContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserGrammarParser.compare1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompare1([NotNull] ParserGrammarParser.Compare1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserGrammarParser.compare1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompare1([NotNull] ParserGrammarParser.Compare1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserGrammarParser.compare2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompare2([NotNull] ParserGrammarParser.Compare2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserGrammarParser.compare2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompare2([NotNull] ParserGrammarParser.Compare2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserGrammarParser.logical_and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogical_and([NotNull] ParserGrammarParser.Logical_andContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserGrammarParser.logical_and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogical_and([NotNull] ParserGrammarParser.Logical_andContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserGrammarParser.logical_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogical_or([NotNull] ParserGrammarParser.Logical_orContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserGrammarParser.logical_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogical_or([NotNull] ParserGrammarParser.Logical_orContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserGrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] ParserGrammarParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserGrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] ParserGrammarParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserGrammarParser.assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssign([NotNull] ParserGrammarParser.AssignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserGrammarParser.assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssign([NotNull] ParserGrammarParser.AssignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserGrammarParser.simple_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimple_stmt([NotNull] ParserGrammarParser.Simple_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserGrammarParser.simple_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimple_stmt([NotNull] ParserGrammarParser.Simple_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserGrammarParser.composite"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComposite([NotNull] ParserGrammarParser.CompositeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserGrammarParser.composite"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComposite([NotNull] ParserGrammarParser.CompositeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserGrammarParser.if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf([NotNull] ParserGrammarParser.IfContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserGrammarParser.if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf([NotNull] ParserGrammarParser.IfContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserGrammarParser.while"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhile([NotNull] ParserGrammarParser.WhileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserGrammarParser.while"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhile([NotNull] ParserGrammarParser.WhileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserGrammarParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmt([NotNull] ParserGrammarParser.StmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserGrammarParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmt([NotNull] ParserGrammarParser.StmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserGrammarParser.stmt_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmt_list([NotNull] ParserGrammarParser.Stmt_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserGrammarParser.stmt_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmt_list([NotNull] ParserGrammarParser.Stmt_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserGrammarParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] ParserGrammarParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserGrammarParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] ParserGrammarParser.ProgramContext context);
}
